teams:
  - name: HyperBugged
    members:
      - Mohammed Asif
      - Aryan Raj
      - Mohammed Sami
      - Yashvardhan Gera
  - name: DBHolic
    members:
      - Aayush Aggarwal
      - Ashish Aryan
      - Prateek Kaistha
      - Ritam Mukherjee
  - name: Etienne
    members:
      - Saurav Shekhar Singh
      - Abhinav Kumar
      - Manu Sehgal
      - Divyam Chandalia
  - name: codeCops
    members:
      - Vivek Nichani
      - Suchismita Sur
      - Ankan Poddar
      - Anwesha Das
  - name: Screeners
    members:
      - Dhruv Rajpoot
      - Tushar sharma
      - Dharini Karthikeyan
      - Pranay Reddy K
  - name: AutoAssist
    members:
      - Sanchit Mehta
      - Sourav Karjee
      - Chitransh Jain
      - Shivam Barsaley